# Generated by Django 5.0.7 on 2024-09-03 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0002_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
